### ISSUE TITLE
Request a space

### ISSUE THREAD

**Issue by ccfz** [lorenzoturrino/makers_bnb#27]
As a guest,
So that I can book a space,
I want to be able to send a requst.

**Comment by ccfz** [comment]
- Create a Booking Model
  - Add requested date to booking model
  - Add space id
  - Host ID 
  - Guest ID
  - Booking status - default pending/confirmed/declined

**Comment by kylebuttner** [comment]
- Create "Request to book"  button on booking listing
-  Redirect to calendar selection page
- Choose single date for booking request
- Submit booking request
- Redirect to spaces listing page
